- name: Install required packages
  become: yes
  yum:
    name: "{{ item}}"
  with_items:
    - qemu-kvm
    - qemu-img
    - libvirt
    - libvirt-python
    - libguestfs-tools
    - virt-install
    - virt-top

- name: Start libvirtd service
  become: yes
  service:
    name: libvirtd
    state: started
    enabled: yes

- name: Install virt-manager
  become: yes
  when: owox_kvm_host_install_virt_manager
  yum:
    name: "{{ item}}"
  with_items:
    - virt-manager
    - xorg-x11-xauth
    - dejavu-lgc-sans-fonts
